spring:
  application:
    name: bookticket

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/bookticket
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework: WARN

jwt:
  secret:
    key: mXbZ0rJj7r5aO6Z5flHh4ZkC+GbA7HGxH0FaGF3kA48=